name: Publish release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:

  github:
    name: github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: "true"

  pypi:
    name: pypi
    runs-on: ubuntu-latest
    needs: github
    environment:
      name: pypi
      url: https://pypi.org/p/qiskit-addon-cutting
    permissions:
      id-token: write
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Install `build` tool
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build distribution
        run: |
          python -m build
      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
